#!/usr/bin/env ruby

require_relative 'lib/scorer.rb'
require_relative 'lib/notification_system.rb'
require 'optparse'

flags = {}

opt_parser = OptionParser.new do |opt|
  opt.banner = "Usage:\n./scorer"
  opt.banner += "\n./scorer [flags]"

  opt.separator  ""
  opt.separator  "flags"

  opt.on("-d", "--daemon", "tell the process to run as a daemon") do
    flags[:purpose] = 'daemon'
  end

  opt.on("-k", "--kill", "kill the daemon process if its running") do
    flags[:purpose] = 'kill'
  end

  opt.on('-l', '--list', 'list all the present matches') do
    flags[:purpose] = 'list'
  end

  opt.on("-h", "--help", "help") do
    flags[:purpose] = 'help'
    puts opt_parser
  end
end

begin
  opt_parser.parse!
rescue OptionParser::ParseError
  puts opt_parser
  exit(0)
end

purpose = flags[:purpose] || 'run'

scorer = Scorer.new(NotificationSystem.new, $0)


case purpose
  when 'daemon'
    scorer.daemon
  when 'kill'
    scorer.kill
  when 'run'
    scorer.run
  when 'list'
    scorer.list
end
