#!/usr/bin/env ruby

require_relative 'lib/scorer.rb'
require_relative 'lib/notification_system.rb'
require 'optparse'

flags = {}
game_index = Integer(ARGV.first) rescue nil unless game_index

opt_parser = OptionParser.new do |opt|
  opt.banner = "Usage:\n./scorer"
  opt.banner += "\n./scorer [Game Index]"
  opt.banner += "\n./scorer [flags]"

  opt.separator  ""
  opt.separator  "flags"

  opt.on("-d", "--daemon=val", "tell the process to run as a daemon", Integer) do |v|
    flags[:purpose] = 'daemon'
    game_index = v
  end

  opt.on("-k", "--kill", "kill the daemon process if its running") do
    flags[:purpose] = 'kill'
  end

  opt.on('-l', '--list', 'list all the present matches') do
    flags[:purpose] = 'list'
  end

  opt.on("-h", "--help", "help") do
    flags[:purpose] = 'help'
    puts opt_parser
  end
end

begin
  opt_parser.parse! unless game_index
rescue OptionParser::ParseError
  puts opt_parser
  exit(0)
end

purpose = flags[:purpose] || 'run'

scorer = Scorer.new(NotificationSystem.new, $0)


case purpose
  when 'daemon'
    scorer.daemon game_index
  when 'kill'
    scorer.kill
  when 'run'
    scorer.run game_index
  when 'list'
    scorer.list
end
